insert into Course (title) values ('Konklux');
insert into Course (title) values ('Lotlux');
insert into Course (title) values ('Rank');
insert into Course (title) values ('Bytecard');
insert into Course (title) values ('Lotstring');
insert into Course (title) values ('Andalax');
insert into Course (title) values ('Y-Solowarm');
insert into Course (title) values ('Asoka');
insert into Course (title) values ('Bigtax');
insert into Course (title) values ('Bigtax');
insert into Course (title) values ('Hatity');
insert into Course (title) values ('Home Ing');
insert into Course (title) values ('Fintone');
insert into Course (title) values ('Otcom');
insert into Course (title) values ('Konklab');
insert into Course (title) values ('It');
insert into Course (title) values ('Cardify');
insert into Course (title) values ('Alpha');
insert into Course (title) values ('Bitwolf');
insert into Course (title) values ('Lotstring');
insert into Course (title) values ('Span');
insert into Course (title) values ('Vagram');
insert into Course (title) values ('Y-find');
insert into Course (title) values ('Stim');
insert into Course (title) values ('Trippledex');
insert into Course (title) values ('Bytecard');
insert into Course (title) values ('Lotstring');
insert into Course (title) values ('Regrant');
insert into Course (title) values ('Keylex');
insert into Course (title) values ('Y-find');
insert into Course (title) values ('Ronstring');
insert into Course (title) values ('Bamity');
insert into Course (title) values ('Bitwolf');
insert into Course (title) values ('Cardify');
insert into Course (title) values ('Flowdesk');
insert into Course (title) values ('Otcom');
insert into Course (title) values ('Namfix');
insert into Course (title) values ('Duobam');
insert into Course (title) values ('Job');
insert into Course (title) values ('Flexidy');
insert into Course (title) values ('Y-Solowarm');
insert into Course (title) values ('Fix San');
insert into Course (title) values ('Biodex');
insert into Course (title) values ('Treeflex');
insert into Course (title) values ('Lotlux');
insert into Course (title) values ('Wrapsafe');
insert into Course (title) values ('Solarbreeze');
insert into Course (title) values ('Stim');
insert into Course (title) values ('Voltsillam');
insert into Course (title) values ('Y-Solowarm');


insert into course_material (url, course_id) values ('Bitchip', 1);
insert into course_material (url, course_id) values ('Treeflex', 2);
insert into course_material (url, course_id) values ('Ronstring', 3);
insert into course_material (url, course_id) values ('Opela', 4);
insert into course_material (url, course_id) values ('Bamity', 5);
insert into course_material (url, course_id) values ('Aerified', 6);
insert into course_material (url, course_id) values ('Greenlam', 7);
insert into course_material (url, course_id) values ('Tin', 8);
insert into course_material (url, course_id) values ('Zaam-Dox', 9);
insert into course_material (url, course_id) values ('Tin', 10);
insert into course_material (url, course_id) values ('Y-find', 11);
insert into course_material (url, course_id) values ('Cardguard', 12);
insert into course_material (url, course_id) values ('Tresom', 13);
insert into course_material (url, course_id) values ('Zontrax', 14);
insert into course_material (url, course_id) values ('Bytecard', 15);
insert into course_material (url, course_id) values ('Home Ing', 16);
insert into course_material (url, course_id) values ('Holdlamis', 17);
insert into course_material (url, course_id) values ('Y-find', 18);
insert into course_material (url, course_id) values ('Daltfresh', 19);
insert into course_material (url, course_id) values ('Pannier', 20);
insert into course_material (url, course_id) values ('Prodder', 21);
insert into course_material (url, course_id) values ('Sonsing', 22);
insert into course_material (url, course_id) values ('Hatity', 23);
insert into course_material (url, course_id) values ('Sonsing', 24);
insert into course_material (url, course_id) values ('Pannier', 25);
insert into course_material (url, course_id) values ('Flexidy', 26);
insert into course_material (url, course_id) values ('Bytecard', 27);
insert into course_material (url, course_id) values ('Greenlam', 28);
insert into course_material (url, course_id) values ('Holdlamis', 29);
insert into course_material (url, course_id) values ('Biodex', 30);
insert into course_material (url, course_id) values ('Zamit', 31);
insert into course_material (url, course_id) values ('Veribet', 32);
insert into course_material (url, course_id) values ('Opela', 33);
insert into course_material (url, course_id) values ('Toughjoyfax', 34);
insert into course_material (url, course_id) values ('Cardify', 35);
insert into course_material (url, course_id) values ('Cardguard', 36);
insert into course_material (url, course_id) values ('Stringtough', 37);
insert into course_material (url, course_id) values ('Veribet', 38);
insert into course_material (url, course_id) values ('Subin', 39);
insert into course_material (url, course_id) values ('Pannier', 40);
insert into course_material (url, course_id) values ('Mat Lam Tam', 41);
insert into course_material (url, course_id) values ('Overhold', 42);
insert into course_material (url, course_id) values ('Overhold', 43);
insert into course_material (url, course_id) values ('Namfix', 44);
insert into course_material (url, course_id) values ('It', 45);
insert into course_material (url, course_id) values ('Hatity', 46);
insert into course_material (url, course_id) values ('Rank', 47);
insert into course_material (url, course_id) values ('Veribet', 48);
insert into course_material (url, course_id) values ('Tin', 49);
insert into course_material (url, course_id) values ('Voltsillam', 50);
